apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadewpq1730-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadewpq1730-tenant-component
    app.kubernetes.io/part-of: loadewpq1730-tenant-app
  name: loadewpq1730-tenant-component
  namespace: loadewpq1730-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadewpq1730-tenant-component
    weight: null
status: {}
